### ISSUE TITLE
Skip errors

### ISSUE THREAD

**Issue by reach4bawer** [darkbitio/aws-recon#137]
Hi, I am trying to get an inventory of an AWS account under an organization. There are certain actions that are blocked and result in access denied. When I try to collect the data using `aws_recon -t 16 -q False -v` 

```
Starting collection with 16 threads...
t0.global.Organizations.describe_organization
t0.global.Organizations.list_handshakes_for_account.0
t0.global.Organizations.AccessDeniedException

Finished in 1 seconds.

Saving resources to /Users/jack/output.json.

/Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': You don't have permissions to access this resource. (Aws::Organizations::Errors::AccessDeniedException)
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-core-3.121.1/lib/seahorse/client/request.rb:72:in `send_request'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws-sdk-organizations-1.62.0/lib/aws-sdk-organizations/client.rb:4468:in `list_policies'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws_recon-0.5.19/lib/aws_recon/collectors/organizations.rb:43:in `collect'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws_recon-0.5.19/lib/aws_recon/aws_recon.rb:49:in `collect'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws_recon-0.5.19/lib/aws_recon/aws_recon.rb:93:in `block in start'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws_recon-0.5.19/lib/aws_recon/aws_recon.rb:86:in `each'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws_recon-0.5.19/lib/aws_recon/aws_recon.rb:86:in `start'
        from /Users/jack/.gem/ruby/3.0.2/gems/aws_recon-0.5.19/bin/aws_recon:8:in `<top (required)>'
        from /Users/jack/.gem/ruby/3.0.2/bin/aws_recon:25:in `load'
        from /Users/jack/.gem/ruby/3.0.2/bin/aws_recon:25:in `<main>'
```

Previously when I just did it for one region I got -

`User: arn:aws:sts::**ACCOUNT_NUMBER**:assumed-role/**ROLE_NAME**/AssumeRoleSession is not authorized to perform: kms:DescribeKey on resource: arn:aws:kms:us-east-1:ACCOUNT_NUMBER:key/KEY_ID (Aws::KMS::Errors::AccessDeniedException)`

skipping all the services wouldn't yield much information, so is there a way to collect as much information that the role allows? I do have the Read Only policy attached to the role but as mentioned some actions are blocked.

**Comment by joshlarsen** [comment]
The `-q` option means to stop on an access error. What happens when you run without it?

**Comment by reach4bawer** [comment]
Same error. I set -q to False so that it wouldn't quit on encountering the error. The script stops as soon as it encounters access denied error.

**Comment by joshlarsen** [comment]
You could skip some services with `-x`. 

For example:

```
aws_recon -t 16 -v -x Organizations,KMS
```

To skip those two services.

**Comment by joshlarsen** [comment]
BTW, @reach4bawer, `-q False` does not have the effect you want. The `False` doesn't do anything. You are specifying `-q`, which will cause collection to stop when an error is caught.
